"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 1000

continuation_prompt = "[â–¸â–¹ ](dimmed white)"

format = """
[î‚¶](surface1)\
$os\
[î‚°](bg:surface2 fg:surface1)\
$username$sudo\
[î‚´](bg:overlay0 fg:surface2)\
$hostname\
[î‚´](bg:blue fg:overlay0)\
$kubernetes\
[î‚´](bg:mauve fg:blue)\
$directory\
[î‚´](fg:mauve bg:peach)\
$c\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$haxe\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$rlang\
$ruby\
$rust\
$perl\
$php\
$python\
$scala\
$swift\
$zig\
$package\
$git_branch\
[î‚´](fg:peach bg:yellow)\
$git_status\
[î‚´](fg:yellow bg:teal)\
$container\
$direnv\
$nix_shell\
$cmd_duration\
$jobs\
$shlvl\
$status\
$fill\
$time\
\n$character\
"""

#right_format = """
#$time
#"""

palette = "catppuccin_mocha"

[c]
format = "[ $symbol]($style)"
style = "fg:base bg:peach"
symbol = "î˜"

[character]
disabled = false
success_symbol = '[ï²](bold fg:blue)'
error_symbol = '[ï²](bold fg:color_red)'

[cmd_duration]
format = "[ ï”  $duration]($style)"
min_time = 2500
min_time_to_notify = 60000
show_notifications = false
style = "fg:base bg:teal"

[container]
format = "[ $symbol $name]($style)"
style = "fg:base bg:teal"
symbol = "ó±‹©"

[dart]
format = "[ $symbol]($style)"
style = "fg:base bg:peach"
symbol = "î™Œ"

[directory]
format = "[ $path]($style)[$read_only]($read_only_style)"
home_symbol = "ï€•"
read_only = " ó°ˆˆ"
read_only_style = "bold fg:crust bg:mauve"
style = "fg:base bg:mauve"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
Apps = "ó°µ†"
Audio = "î´ƒ"
Crypt = "ó°Œ¾"
Desktop = "ï„ˆ"
Development = "î»´"
Documents = "ó°ˆ™"
Downloads = "ó°‰"
Dropbox = "ï…«"
Games = "ó°Š´"
Keybase = "ó°¯„"
Music = "ó°„"
Pictures = "ï€¾"
Public = "ï‡¡"
Quickemu = "ï’‡"
Studio = "ó°¡‡"
Vaults = "ó°Œ¿"
Videos = "ï€½"
Volatile = "ó±ªƒ"
Websites = "ó°–Ÿ"
Zero = "ó°¡"
nix-config = "ó±„…"

[direnv]
allowed_msg = ""
denied_msg = ""
disabled = false
format = "[ $loaded]($style)"
loaded_msg = "ó°"
not_allowed_msg = ""
style = "fg:base bg:teal"
symbol = ""
unloaded_msg = "ó°™§"

[dotnet]
format = "[ $symbol]($style)"
style = "fg:base bg:peach"
symbol = "î™ˆ"

[elixir]
format = "[ $symbol]($style)"
style = "fg:base bg:peach"
symbol = "î˜­"

[elm]
format = "[ $symbol]($style)"
style = "fg:base bg:peach"
symbol = "î˜¬"

[erlang]
format = "[ $symbol]($style)"
style = "fg:base bg:peach"
symbol = "ïˆ¿"

[fill]
symbol = ' '

[git_branch]
format = "[ $symbol $branch]($style)"
style = "fg:base bg:peach"
symbol = "îœ¥"

[git_status]
ahead = "ó°œ¹"
behind = "ó°œ°"
conflicted = "ó°³¤ "
deleted = "ï‘˜ "
diverged = "ï“’"
format = "[ $all_status$ahead_behind]($style)"
modified = "ï‘™ "
renamed = "ï‘š "
staged = "ï‘— "
stashed = "ï‘¡ "
style = "fg:base bg:yellow"
typechanged = "ï“¬ "
untracked = "ï’£ "
up_to_date = "ó°¤“"

[golang]
format = "[ $symbol]($style)"
style = "fg:base bg:peach"
symbol = "î˜§"

[haskell]
format = "[ $symbol]($style)"
style = "fg:base bg:peach"
symbol = "ó°²’"

[haxe]
format = "[ $symbol]($style)"
style = "fg:base bg:peach"
symbol = "î™¦"

[hostname]
disabled = false
format = "[ $hostname]($style)[$ssh_symbol](bg:overlay0 fg:maroon)"
ssh_only = false
ssh_symbol = " ó°–ˆ"
style = "bg:overlay0 fg:red"

[java]
format = "[ $symbol]($style)"
style = "fg:base bg:peach"
symbol = "ó°¬·"

[jobs]
format = "[ $symbol $number]($style)"
style = "fg:base bg:teal"
symbol = "ó°£–"

[julia]
format = "[ $symbol]($style)"
style = "fg:base bg:peach"
symbol = "î˜¤"

[kotlin]
format = "[ $symbol]($style)"
style = "fg:base bg:peach"
symbol = "î˜´"

[kubernetes]
format = "[ $symbol ($cluster)]($style)"
style = "fg:base bg:blue"
detect_folders = [ "k8s" ]
disabled = false
contexts = [
{ context_pattern = ".*stage.*", style = "fg:prev_fg bg:prev_bg italic", symbol = "ó±¤ "  },
{ context_pattern = ".*prod.*", style = "fg:text bg:prev_bg bold", symbol = "ó±ƒ¾ " },
]

[lua]
format = "[ $symbol]($style)"
style = "fg:base bg:peach"
symbol = "î˜ "

[nim]
format = "[ $symbol]($style)"
style = "fg:base bg:peach"
symbol = "î™·"

[nix_shell]
format = "[ $symbol]($style)"
style = "fg:base bg:teal"
symbol = "ó±„…"

[nodejs]
format = "[ $symbol]($style)"
style = "fg:base bg:peach"
symbol = "ï‹¯"

[os]
disabled = false
format = "$symbol"
style = ""

[os.symbols]
AlmaLinux = "[ïŒ](fg:text bg:surface1)"
Alpine = "[ïŒ€](fg:blue bg:surface1)"
Amazon = "[ï‰°](fg:peach bg:surface1)"
Android = "[îœ](fg:green bg:surface1)"
Arch = "[ó°£‡](fg:sapphire bg:surface1)"
Artix = "[ïŒŸ](fg:sapphire bg:surface1)"
CentOS = "[ïŒ„](fg:mauve bg:surface1)"
Debian = "[ïŒ†](fg:red bg:surface1)"
DragonFly = "[î»¸](fg:teal bg:surface1)"
EndeavourOS = "[ïŒ¢](fg:mauve bg:surface1)"
Fedora = "[ïŒŠ](fg:blue bg:surface1)"
FreeBSD = "[ïŒŒ](fg:red bg:surface1)"
Garuda = "[ïŒ·](fg:sapphire bg:surface1)"
Gentoo = "[ïŒ](fg:lavender bg:surface1)"
Illumos = "[ïŒ¦](fg:peach bg:surface1)"
Kali = "[ïŒ§](fg:blue bg:surface1)"
Linux = "[ïŒš](fg:yellow bg:surface1)"
Macos = "[ïŒ‚](fg:text bg:surface1)"
Manjaro = "[ïŒ’](fg:green bg:surface1)"
Mint = "[ó°£­](fg:teal bg:surface1)"
NixOS = "[ïŒ“](fg:sky bg:surface1)"
OpenBSD = "[ïŒ¨](fg:yellow bg:surface1)"
Pop = "[ïŒª](fg:sapphire bg:surface1)"
Raspbian = "[ïŒ•](fg:maroon bg:surface1)"
RedHatEnterprise = "[î½](fg:red bg:surface1)"
Redhat = "[î½](fg:red bg:surface1)"
RockyLinux = "[ïŒ«](fg:green bg:surface1)"
SUSE = "[ïŒ”](fg:green bg:surface1)"
Solus = "[ïŒ­](fg:blue bg:surface1)"
Ubuntu = "[î¯‰](fg:peach bg:surface1)"
Unknown = "[ï™](fg:text bg:surface1)"
Void = "[ïŒ®](fg:green bg:surface1)"
Windows = "[ó°–³](fg:sky bg:surface1)"
openSUSE = "[ïŒ”](fg:green bg:surface1)"

[package]
format = "[ $version]($style)"
style = "fg:base bg:peach"
version_format = "$raw"

[perl]
format = "[ $symbol]($style)"
style = "fg:base bg:peach"
symbol = "î™¾"

[php]
format = "[ $symbol]($style)"
style = "fg:base bg:peach"
symbol = "ó°ŒŸ"

[python]
format = '[ $symbol ($version) ]($style)'
style = "fg:base bg:peach"
symbol = "î´›"

[rlang]
format = "[ $symbol]($style)"
style = "fg:base bg:peach"
symbol = "î·"

[ruby]
format = "[ $symbol]($style)"
style = "fg:base bg:peach"
symbol = "îœ¹"

[rust]
format = "[ $symbol]($style)"
style = "fg:base bg:peach"
symbol = "î¨"

[scala]
format = "[ $symbol]($style)"
style = "fg:base bg:peach"
symbol = "îš"

[shlvl]
disabled = false
format = "[ $symbol]($style)"
repeat = false
style = "fg:surface1 bg:teal"
symbol = "ó±†ƒ"
threshold = 3

[status]
disabled = false
format = "$symbol"
map_symbol = true
not_executable_symbol = "[î‚´](fg:teal bg:pink)[ î¯ $common_meaning](fg:red bg:pink)[î‚´](fg:pink)"
not_found_symbol = "[î‚´](fg:teal bg:pink)[ ó°©Œ $common_meaning](fg:red bg:pink)[î‚´](fg:pink)"
sigint_symbol = "[î‚´](fg:teal bg:pink)[ ï‰– $signal_name](fg:red bg:pink)[î‚´](fg:pink)"
signal_symbol = "[î‚´](fg:teal bg:pink)[ âš¡ $signal_name](fg:red bg:pink)[î‚´](fg:pink)"
style = ""
success_symbol = "[î‚´](fg:teal)"
symbol = "[î‚´](fg:teal bg:pink)[ ï¡ $status](fg:red bg:pink)[î‚´](fg:teal)"

[sudo]
disabled = true
format = "[ $symbol]($style)"
style = "fg:rosewater bg:surface2"
symbol = "ó°Œ‹"

[swift]
format = "[ $symbol]($style)"
style = "fg:base bg:peach"
symbol = "îš™"

[time]
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = '%H:%M'

[username]
format = "[ $user]($style)"
show_always = true
style_root = "fg:red bg:surface2"
style_user = "fg:green bg:surface2"

[username.aliases]
"vulcan.gheorghe" = "î·…"
user = ""
root = "ó°‡´"

[hostname.aliases]
0624EITR1018 = "peregrine"

[zig]
format = "[ $symbol]($style)"
style = "fg:base bg:peach"
symbol = "îš©"

# https://gist.github.com/ashleysommer/441d1df2cbd6a03113cd85f946f9cc0d
[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[palettes.monokai_dark_gogh]
color_fg0 = '#f8f8f2'
color_bg0 = '#272822'
color_bg1 = '#3c3836'
color_bg3 = '#75715e'
color_blue = '#66d9ef'
color_aqua = '#2aa198'
color_green = '#a6e22e'
color_orange = '#fc9867'
color_purple = '#ab9df2'
color_red = '#ff6188'
color_yellow = '#ffd866'

# https://starship.rs/presets/catppuccin-powerline

[palettes.catppuccin_mocha]
base = "#1e1e2e"
blue = "#89b4fa"
crust = "#11111b"
flamingo = "#f2cdcd"
green = "#a6e3a1"
lavender = "#b4befe"
mantle = "#181825"
maroon = "#eba0ac"
mauve = "#cba6f7"
overlay0 = "#6c7086"
overlay1 = "#7f849c"
overlay2 = "#9399b2"
peach = "#fab387"
pink = "#f5c2e7"
red = "#f38ba8"
rosewater = "#f5e0dc"
sapphire = "#74c7ec"
sky = "#89dceb"
subtext0 = "#a6adc8"
subtext1 = "#bac2de"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"
teal = "#94e2d5"
text = "#cdd6f4"
yellow = "#f9e2af"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
